[project]
name = "source-collector-admin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nicegui>=2.19.0",
    "pdap-access-manager==0.4.1",
]
